In [1]:
import pandas as pd
import subprocess
from functools import reduce
import numpy as np
import umap
from plotnine import *
import os
import pickle

/gpfs/commons/home/anewbury/miniconda/envs/jupyter/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Explore 1000 genomes data

In [8]:
populations = pd.read_csv('/gpfs/commons/datasets/1000genomes/phase3/20131219.populations.tsv',sep='\t',engine='python')
superpopulations = pd.read_csv('/gpfs/commons/datasets/1000genomes/phase3/20131219.superpopulations.tsv', sep='\t',engine='python')

In [10]:
populations.groupby('Super Population')['Final Phase Samples'].sum()

Super Population
AFR    669.0
AMR    352.0
EAS    515.0
EUR    505.0
SAS    494.0
Name: Final Phase Samples, dtype: float64

Choose K=5 for admixture files; read in .ped and .map files

In [ ]:
def prep_1000genomes_bed_file(root_dir, output):
    # change map and ped files to bed format
    # major allele set to A2 (If a binary fileset was originally loaded, --keep-allele-order forces the original A1/A2 allele encoding to be preserved; otherwise, the major allele is set to A2)
    plink_extract = f'''
    module load plink/1.9 && plink --file {root_dir}/release-20130502-supporting/admixture_files/ALL.wgs.phase3_shapeit2_filtered.20141217.maf0.05 \
        --make-bed \
        --out {output}
    '''
    result = subprocess.run(plink_extract, shell=True, check=True, executable="/bin/bash")

In [8]:
def read_in_igsr_samples(igsr_samples_filepath,bfile_path=None):
      # read in, subset to 2504, order correctly (if bfile path is not None)
      igsr_samples = pd.read_csv(igsr_samples_filepath,sep='\t')

      if bfile_path is not None:
            fam_df = pd.read_csv(f'{bfile_path}.fam',sep='\s+',header=None)
            fam_df.columns = ['FID','IID'] + fam_df.columns[2:].tolist()
            iid_order = fam_df['IID'].values
            igsr_samples = igsr_samples[igsr_samples['Sample name'].isin(iid_order)].copy()
            igsr_samples["Sample name"] = pd.Categorical(igsr_samples["Sample name"], categories=iid_order, ordered=True)
            igsr_samples = igsr_samples.sort_values("Sample name").reset_index(drop=True)
      igsr_samples["Superpopulation code"] = igsr_samples["Superpopulation code"].str.split(",").str[0] # chose first for sample with EUR,AFR superpopulation code
      igsr_samples.rename(columns={'Sample name':'IID'},inplace=True)
      igsr_samples['FID'] = igsr_samples['IID']

      return igsr_samples

def calculate_maf_by_superpop(igsr_samples_filepath,intermediate_file_dir,bfile_path,output):
      # Calculate allele frequencies in five superpopulations
      # generate superpopulation cluster file
      igsr_samples = read_in_igsr_samples(igsr_samples_filepath,bfile_path)
      igsr_samples[['FID','IID','Superpopulation code']].to_csv(f'{intermediate_file_dir}/superpop.clst',index=False,header=False,sep='\t')
      # calculate maf by superpop
      plink_freq = f''' module load plink/1.9 && 
      plink --bfile {bfile_path} \
            --freq \
            --within {intermediate_file_dir}/superpop.clst \
            --out {output}
      '''
      result = subprocess.run(plink_freq, shell=True, check=True, executable="/bin/bash")

      maf_by_superpop = pd.read_csv(f'{intermediate_file_dir}/maf_by_superpop.frq.strat',sep='\s+')
      return maf_by_superpop

In [ ]:
def sun_generate_sim_data(bfile_path, maf_by_superpop_filepath,
                          intermediate_file_dir,intermediate_file_suffix,output_dir,output_file_suffix,
                          ps,num_markers_assoc,e,extra_subgroups_size,M,num_clinical_assoc):
    '''
    Generate synthetic data similar to Sun et al. (Multi-view biclustering for genotype-phenotype association studies of complex diseases)
    using 1000 Genomes Phase 3 data. Use admixture files which contain 193634 markers with MAF>5% and 2504 individuals. 

    PARAMS:
    bfile_path: path to bfile for genetic data
    maf_by_superpop_filepath: plink generated .frq.strat file for maf within each superpopulation group. don't include .frq.strat suffix in filename.
    intermediate_file_dir: dir to write intermediate files to (when using plink for example)
    intermediate_file_suffix: such that if multiple simulations are created, each is distinctly defined
    intermediate_file_suffix: such that if multiple simulations are created, each is distinctly defined - suffic for C and simulated data pkl file
    output_dir: where to write output genetic data matrix (X) in form of plink bfile, and clinical data matrix C
    M: number of clinical features (right now assuming all from one domain & all binary)
    ps: variable controlling how much population stratification is affecting geno-pheno relationship (needs to be in range(0,1,size=0.1)) 
    (0-> pick SNPs in bottom 10% by allele frequency variance i.e. little pop. strat., 0.9-> pick SNPS in top 10% by allele frequency variance i.e. large pop. strat.)
    num_markers_assoc: number of markers with an associated with subtype classification (if rij>int(0.4*markers_assoc) then subject i in subgroup j)
    e: relative effect that genetic variation contributed to the effect of the phenotype. e in [0,1]. (decreased e means higher level of disagreement between genotypic and phenotypic subgroups)
    num_clinical_assoc: number of clinical features associated with subtype classification (same for all subtypes)
    extra_subgroups_size: number of people in s3 and s4 (selected at random)

    outputs:
    C: clinical data matrix (num samples x M)
    in pickle file (all simulation metadata):
    genetic_subgroups: genetic subgroup assignments for all individuals
    phenotypic_subgroups: phenotypic subgroup assignments for all individuals
    iid_order: IIDs in order (to align to clinical data matrix)
    markers_assoc_dict: for each genetic subgroup, IDs of genetic markers selected to be associated
    clinical_assoc_df: for each phenotypic subgroup, index of clinical variables selected to be associated (and their selected assoc. strength)

    '''
    assert num_clinical_assoc<M, "num_clinical_assoc cannot exceed M"

    # 1. Read in allele frequencies per 5 superpopulations to estimate af variance across groups
    maf_by_superpop = pd.read_csv(f'{maf_by_superpop_filepath}.frq.strat',sep='\s+')
    superpopulations = maf_by_superpop['CLST'].unique()
    maf_by_superpop = maf_by_superpop.pivot(index=['SNP'],columns='CLST',values='MAF').reset_index()
    assert maf_by_superpop.shape[0] == 193634
    maf_by_superpop['af_variance'] = maf_by_superpop[superpopulations].var(axis=1)
    maf_by_superpop['af_var_decile'] = (pd.qcut(maf_by_superpop['af_variance'], 10, labels=False))/10 # discretize into equal size buckets based on deciles


    # 2. Generate genetic subgroups
    genetic_subgroups = []
    markers_assoc_dict = {} # names of the markers that are associated with each subgroup
    for genetic_subgroup in range(2):
        # Select SNP group based on num_markers_assoc and ps
        assert maf_by_superpop[maf_by_superpop['af_var_decile']==ps].shape[0]>num_markers_assoc, f"number of genetic features assoc. ({num_markers_assoc}) is too large, only {maf_by_superpop[maf_by_superpop['af_var_decile']==ps].shape[0]} markers in decile {ps} group"
        markers_assoc = maf_by_superpop[maf_by_superpop['af_var_decile']==ps].sample(n=num_markers_assoc, replace=False)['SNP'].values.tolist()
        markers_assoc_dict[genetic_subgroup] = markers_assoc
        assert len(set(markers_assoc))==len(markers_assoc) # make sure ped file has unique rows

        
        # extract selected markers
        with open(f'{intermediate_file_dir}/markers_assoc_g{genetic_subgroup}_{intermediate_file_suffix}.txt','w') as f:
            for snp in markers_assoc:
                f.write(snp + "\n")
        
        # extract select markers and get marker values for each individual (0 - no copies of minor allele, 1 - 1 copy of minor allele, 2 - 2 copies of minor allele)
        plink_extract = f'''
        module load plink/1.9 && plink --bfile {bfile_path} \
            --extract {intermediate_file_dir}/markers_assoc_g{genetic_subgroup}_{intermediate_file_suffix}.txt \
            --make-bed \
            --recode A \
            --out {intermediate_file_dir}/subset_markers_g{genetic_subgroup}_{intermediate_file_suffix}
        '''
        result = subprocess.run(plink_extract, shell=True, check=True, executable="/bin/bash")

        # read in to get genotype counts
        raw = pd.read_csv(f'{intermediate_file_dir}/subset_markers_g{genetic_subgroup}_{intermediate_file_suffix}.raw',sep="\s+")
        geno = raw.drop(columns=['FID','IID','PAT','MAT','SEX','PHENOTYPE'])
        # assert they are all ≤ 0.5 (i.e., A1 is the minor allele)
        assert (geno.sum(axis=0) / (2 * geno.shape[0]) <= 0.5).all(), "Some SNPs have A1 frequency > 0.5"
        geno_cols = [col for col in raw.columns if not col in ['FID','IID','PAT','MAT','SEX','PHENOTYPE']]
        assert len(geno_cols) == num_markers_assoc
        raw[geno_cols] = (raw[geno_cols] > 0).astype(int) # recode s.t. values 1 and 2 map to 1
        genetic_subgroup_df = raw.set_index('IID')[geno_cols].sum(axis=1).reset_index(name=f'r')
        genetic_subgroup_df['genetic_subgroup'] = genetic_subgroup
        
        deciles, bins = pd.qcut(genetic_subgroup_df["r"], 10, labels=False, retbins=True)
        genetic_subgroup_df[f'subgroup'] =genetic_subgroup_df['r']>bins[-3] # Top 20% of people per r
        genetic_subgroups.append(genetic_subgroup_df)
    genetic_subgroups = pd.concat(genetic_subgroups)

    # 3. Generate phenotypic subgroups
    iid_order = raw.IID.values # can use raw file from whichever subgroup, since IID always in same order
    # can just use bins[-4] - somewhat equivalent to 7.5
    phenotypic_subgroups = []
    for phenotypic_subgroup in range(2):
        phenotypic_subgroup_df = genetic_subgroups[genetic_subgroups['genetic_subgroup']==phenotypic_subgroup][['IID','r']].copy()
        phenotypic_subgroup_df['phenotypic_subgroup'] = phenotypic_subgroup
        phenotypic_subgroup_df['subgroup'] = phenotypic_subgroup_df['r']*e + np.random.randn(len(phenotypic_subgroup_df)) > bins[-4]*e
        phenotypic_subgroups.append(phenotypic_subgroup_df)
    for phenotypic_subgroup in range(2,4):
        # randomly select extra_subgroups_size people
        randomly_selected = pd.Series(iid_order).sample(extra_subgroups_size).values.tolist() 
        phenotypic_subgroup_df = pd.DataFrame(iid_order,columns=['IID'])
        phenotypic_subgroup_df['r'] = None
        phenotypic_subgroup_df['phenotypic_subgroup'] = phenotypic_subgroup
        phenotypic_subgroup_df['subgroup'] = phenotypic_subgroup_df['IID'].isin(randomly_selected)
        phenotypic_subgroups.append(phenotypic_subgroup_df)
    phenotypic_subgroups = pd.concat(phenotypic_subgroups)

    # 4. simulate M binary clinical features
    # start with baseline probabiliyies
    probs = np.full((len(iid_order), M), 0.1, dtype=float) # baseline prob of clinical feature is 0.1
    clinical_assoc_df_rows = [] # index of clinical vars that are associated (and their strength)
    for phenotypic_subgroup in range(4):
        # index of randomly chosen, associated clinical variables 
        assoc_idx = np.random.choice(M, size=num_clinical_assoc, replace=False) 
        np.random.shuffle(assoc_idx)       
        n1 = num_clinical_assoc // 3 # 1/3 who get P 0.6
        n2 = 2 * num_clinical_assoc // 3 # 1/3 who get P 0.5
        # get those who are in the subgroup
        mask = ((phenotypic_subgroups["phenotypic_subgroup"] == phenotypic_subgroup) & (phenotypic_subgroups["subgroup"]))
        subj_ids = phenotypic_subgroups.loc[mask, "IID"].unique()
        # map subject IDs to row indices 
        row_idx = [i for i, iid in enumerate(iid_order) if iid in subj_ids]
        probs[np.ix_(row_idx, assoc_idx[:n1])] = 0.6
        probs[np.ix_(row_idx, assoc_idx[n1:n2])] = 0.5
        probs[np.ix_(row_idx, assoc_idx[n2:])] = 0.4
        clinical_assoc_df_rows += [
        {"phenotypic_subgroup": phenotypic_subgroup, "strength": 0.6, "indices": assoc_idx[:n1]},
        {"phenotypic_subgroup": phenotypic_subgroup, "strength": 0.5, "indices": assoc_idx[n1:n2]},
        {"phenotypic_subgroup": phenotypic_subgroup, "strength": 0.4, "indices": assoc_idx[n2:]},
        ]
    clinical_assoc_df = pd.DataFrame(clinical_assoc_df_rows)

    # write C
    C = (np.random.rand(len(iid_order), M) < probs).astype(int)
    np.save(f"{output_dir}/C_{output_file_suffix}.npy", C)

    # write simulation metadata
    bundle = {
    "iid_order": iid_order,                          # list/array
    "genetic_subgroups": genetic_subgroups,          # list/array/Series
    "phenotypic_subgroups": phenotypic_subgroups,    # list/array/Series
    "markers_assoc": markers_assoc_dict,             # dict: gen_subgroup -> [marker_id, ...]
    "clinical_assoc": clinical_assoc_df              # pandas DataFrame
    }
    with open(f"{output_dir}/simulation_metadata_{output_file_suffix}.pkl", "wb") as f:
        pickle.dump(bundle, f, protocol=pickle.HIGHEST_PROTOCOL)

    return genetic_subgroups, phenotypic_subgroups, C, iid_order, markers_assoc_dict, clinical_assoc_df

In [ ]:
intermediate_file_dir ='/gpfs/commons/groups/gursoy_lab/anewbury/unsupervised_pheno/data/simulations/intermediate_plink'
root_dir = '/gpfs/commons/datasets/1000genomes'
igsr_samples_filepath = '/gpfs/commons/groups/gursoy_lab/anewbury/unsupervised_pheno/data/simulations/input/igsr_samples.tsv'
output_dir = '/gpfs/commons/groups/gursoy_lab/anewbury/unsupervised_pheno/data/simulations/output'

genetic_subgroups,phenotypic_subgroups,C,iid_order,markers_assoc_dict, clinical_assoc_df = sun_generate_sim_data(bfile_path=f'{output_dir}/X', maf_by_superpop_filepath=f'{intermediate_file_dir}/maf_by_superpop', intermediate_file_dir=intermediate_file_dir,
                                        intermediate_file_suffix='',output_dir = output_dir,  output_file_suffix='TEST',
                                      ps=0, num_markers_assoc=2000, e=0.5,extra_subgroups_size=200, M=100,num_clinical_assoc=10) # intermediate_file_suffix important if run in parallel

## Determine the effect of ps on confounding by superpopulation

In [135]:
ps_list = np.round(np.arange(0, 1.0, 0.1),1)
e_list = np.round(np.arange(0, 1.1, 0.1),1)

In [9]:
igsr_samples = read_in_igsr_samples(igsr_samples_filepath, bfile_path=f'{output_dir}/X')

In [177]:
def generate_umap_plot(mode, var_list, color_col, color_label, output_dir):
    '''Generate UMAP plot of C across different values of variable spcified in 'mode' 
    (values in var_list), colored by color_df (which must have a column IID)'''
    plot_dfs = []
    for var in var_list:
        if mode == 'ps':
            output_suffix = f'ps_{var}_e_0.5'
            with open(f"{output_dir}/simulation_metadata_{output_suffix}.pkl", "rb") as f:
                simulation_metadata = pickle.load(f)
            color_df = read_in_igsr_samples(igsr_samples_filepath, bfile_path=f'{output_dir}/X')
        else:
            assert mode=='e', "only works with modes ps and e so far"
            output_suffix = f'ps_0.5_e_{var}'
            with open(f"{output_dir}/simulation_metadata_{output_suffix}.pkl", "rb") as f:
                simulation_metadata = pickle.load(f)
            genetic_subgroups = simulation_metadata['genetic_subgroups']
            genetic_subgroups['subgroup_value'] = np.where(genetic_subgroups['subgroup'],genetic_subgroups['genetic_subgroup'],'') # change this to one label per person
            genetic_subgroups_concat = genetic_subgroups.groupby('IID')['subgroup_value'].apply(clean_join).reset_index()
            genetic_subgroups_concat["IID"] = pd.Categorical(genetic_subgroups_concat["IID"], categories=iid_order, ordered=True)
            color_df = genetic_subgroups_concat.copy()
        C = np.load(f'{output_dir}/C_{output_suffix}.npy')# pick e=0.5

        reducer = umap.UMAP()
        embedding = reducer.fit_transform(C)

        plot_df = (pd.DataFrame(embedding, columns=["UMAP1", "UMAP2"], index=simulation_metadata['iid_order']).
                    rename_axis("IID").reset_index().merge(color_df[['IID',color_col]], on='IID',how='inner'))
        
        assert plot_df[plot_df[color_col].isna()].shape[0] == 0
        plot_df[mode] = var
        plot_dfs.append(plot_df)
    plot_dfs = pd.concat(plot_dfs)

    # --- Plot with plotnine ---
    p = (
        ggplot(plot_dfs, aes("UMAP1", "UMAP2", color=color_col))
        + geom_point(alpha=0.7, size=2)
        + labs(title=r"UMAP of clinical data at different $p_s$ levels", color=color_label)
        + facet_wrap(f'~{mode}',ncol=2,scales='free')
        + theme_minimal()
        + theme(figure_size=(8, 12),legend_title=element_text(size=9))
    )
    p.save(f'{output_dir}/umap_clinical_{mode}.pdf',dpi=300)

In [ ]:
generate_umap_plot(mode='ps', var_list=[0.1,0.5], color_col='Superpopulation name', color_label='Superpopulation', output_dir=output_dir)

In [178]:
generate_umap_plot(mode='e', var_list=[0.1,0.5], color_col='subgroup_value', color_label='Genetic Subgroup', output_dir=output_dir)

/gpfs/commons/home/anewbury/miniconda/envs/jupyter/lib/python3.9/site-packages/plotnine/ggplot.py:587: PlotnineWarning: Saving 8 x 12 in image.
/gpfs/commons/home/anewbury/miniconda/envs/jupyter/lib/python3.9/site-packages/plotnine/ggplot.py:588: PlotnineWarning: Filename: /gpfs/commons/groups/gursoy_lab/anewbury/unsupervised_pheno/data/simulations/output/umap_clinical_e.pdf

In [137]:
def clean_join(values):
    # remove empty strings
    vals = sorted(set(v for v in values if v != ''), key=lambda x: int(x))
    return ','.join(vals)

### Run GWAS with and without PCs and see how much genetic coefficients change 
At different levels of population stratification

In [ ]:
pcs = pd.read_csv(f'{output_dir}/pcs.txt',sep='\t')
covar = pcs.merge(igsr_samples[['IID','Sex']], on='IID',how='inner')
# probably cleaner way to do this
covar[['FID','IID']+[f'PC{i}' for i in range(1,11)]+['Sex']].set_index('FID').to_csv(f'{intermediate_file_dir}/COVARIATE_FILE')
covar[['FID','IID']+['Sex']].set_index('FID').to_csv(f'{intermediate_file_dir}/COVARIATE_FILE_NOPS')

for ps, e in product(ps_list, e_list):
    output_suffix = f'ps_{ps}_e_{e}'
    for cov_included in [False,True]:
        if cov_included:
            cov_file_suffix = ''
        else:
            cov_file_suffix = '_NOPS'
        for phenotypic_subgroup in range(4): # subgroup 0 & 1 should be affected, subgroup 2 & 3 shouldn't be affected (randomly chosen people)
            with open(f"{output_dir}/simulation_metadata_{output_suffix}.pkl", "rb") as f:
                simulation_metadata = pickle.load(f)
            phenotypic_subgroups = simulation_metadata['phenotypic_subgroups']
            pheno = phenotypic_subgroups[phenotypic_subgroups['phenotypic_subgroup']==phenotypic_subgroup][['IID','subgroup']].rename(columns={'subgroup':'Phenotype'})
            pheno['FID'] = pheno['IID']
            pheno['Phenotype'] = pheno['Phenotype'].astype(int)
            pheno[['FID','IID','Phenotype']].set_index('FID').to_csv(f'{intermediate_file_dir}/PHENOTYPE_FILE_Subgroup{phenotypic_subgroup}')

            result = subprocess.run(f'module unload plink && module load plink/2.0a5.13 && plink --bfile {output_dir}/X\
                                --covar {intermediate_file_dir}/COVARIATE_FILE{cov_file_suffix} --covar-variance-standardize\
                                --pheno {intermediate_file_dir}/PHENOTYPE_FILE_Subgroup{phenotypic_subgroup}\
                                --glm omit-ref\
                                --out {output_dir}/GWAS_RESULTS/PhenotypicSubgroup_{phenotypic_subgroup}_Geno_Cov_{cov_included}_ps_{ps}_e_{e}\
                                --1 --no-pheno', shell=True, capture_output=True, text=True, executable='/bin/bash')
            result.check_returncode()

for subgroup 0, what's the difference in coeff effect size when covs included or not

In [79]:
# general idea: fit crude and adjusted model and if beta changes by more than 10%, we conclude that ancestry is a confounder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

phenotypic_subgroup = 0
all_plink_results = []
for cov_included in [False,True]:
    plink_results = pd.read_csv(f'{os.path.dirname(intermediate_file_dir)}/output/RESULTS_FILE_Subgroup{phenotypic_subgroup}_Geno_Cov{cov_included}.Phenotype.glm.logistic.hybrid',sep='\t')
    print(plink_results.shape)
    plink_results = plink_results[plink_results['TEST']=='ADD'].copy()
    plink_results['marker_assoc'] = plink_results['ID'].isin(markers_assoc_dict[phenotypic_subgroup]) # ground truth from simulations
    # using significance level 5e-8, what is the accuracy of association test
    plink_results['significant'] = plink_results['P'] < 5e-8 # predicted associated
    print(plink_results[plink_results['P'] < 5e-8].shape[0])
    accuracy = accuracy_score(plink_results["marker_assoc"], plink_results["significant"])
    precision = precision_score(plink_results["marker_assoc"], plink_results["significant"])
    recall = recall_score(plink_results["marker_assoc"], plink_results["significant"])
    f1 = f1_score(plink_results["marker_assoc"], plink_results["significant"])
    print(cov_included)
    print(accuracy)
    print(precision)
    print(recall)
    print(f1)
    plink_results['cov_included'] = cov_included
    all_plink_results.append(plink_results)
all_plink_results = pd.concat(all_plink_results)

(387268, 17)
128086
False
0.3440924631004886
0.012023171931358618
0.77
0.02367664468121089
(1161804, 17)
0
True
0.989671235423531
0.0
0.0
0.0

/gpfs/commons/home/anewbury/miniconda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

In [83]:
wide = (all_plink_results
        .pivot(index='ID', columns='cov_included', values='OR')
        .rename(columns={False:'OR_no_cov', True:'OR_with_cov'})
        .reset_index()
)

# Calculate relative change
wide['relative_change'] = abs(wide['OR_with_cov'] - wide['OR_no_cov']) / wide['OR_no_cov']
print(wide['relative_change'].mean())
wide

0.7869915795402833

cov_included            ID   OR_no_cov  OR_with_cov  relative_change
0              10:10002676    0.407327     0.793863         0.948957
1             10:100033081   60.261000     0.607603         0.989917
2              10:10004698   68.774400     0.331431         0.995181
3             10:100068607    0.754749     1.165830         0.544659
4             10:100076982    0.508965     0.817929         0.607044
...                    ...         ...          ...              ...
193629          9:99959341    0.811283     1.173930         0.447004
193630          9:99979829  124.290000     0.521338         0.995805
193631          9:99981843    0.515383     1.016670         0.972649
193632           9:9998777    0.437162     0.953639         1.181432
193633          9:99987850    0.537876     1.016690         0.890194

[193634 rows x 4 columns]

In [85]:
# should see no change wi†h this subgroup
phenotypic_subgroup = 2
all_plink_results = []
for cov_included in [False,True]:
    plink_results = pd.read_csv(f'{os.path.dirname(intermediate_file_dir)}/output/RESULTS_FILE_Subgroup{phenotypic_subgroup}_Geno_Cov{cov_included}.Phenotype.glm.logistic.hybrid',sep='\t')
    print(plink_results.shape)
    plink_results = plink_results[plink_results['TEST']=='ADD'].copy()
    plink_results['marker_assoc'] = False # ground truth from simulations
    # using significance level 5e-8, what is the accuracy of association test
    plink_results['significant'] = plink_results['P'] < 5e-8 # predicted associated
    print(plink_results[plink_results['P'] < 5e-8].shape[0])
    accuracy = accuracy_score(plink_results["marker_assoc"], plink_results["significant"])
    precision = precision_score(plink_results["marker_assoc"], plink_results["significant"])
    recall = recall_score(plink_results["marker_assoc"], plink_results["significant"])
    f1 = f1_score(plink_results["marker_assoc"], plink_results["significant"])
    print(cov_included)
    print(accuracy)
    print(precision)
    print(recall)
    print(f1)
    plink_results['cov_included'] = cov_included
    all_plink_results.append(plink_results)
all_plink_results = pd.concat(all_plink_results)

(387268, 17)
0

/gpfs/commons/home/anewbury/miniconda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
/gpfs/commons/home/anewbury/miniconda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
/gpfs/commons/home/anewbury/miniconda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.

False
1.0
0.0
0.0
0.0
(1161804, 17)
0
True
1.0
0.0
0.0
0.0

/gpfs/commons/home/anewbury/miniconda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
/gpfs/commons/home/anewbury/miniconda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
/gpfs/commons/home/anewbury/miniconda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.

In [86]:
wide = (all_plink_results
        .pivot(index='ID', columns='cov_included', values='OR')
        .rename(columns={False:'OR_no_cov', True:'OR_with_cov'})
        .reset_index()
)

# Calculate relative change
wide['relative_change'] = abs(wide['OR_with_cov'] - wide['OR_no_cov']) / wide['OR_no_cov']
print(wide['relative_change'].mean())
wide

0.029815247828271215

cov_included            ID  OR_no_cov  OR_with_cov  relative_change
0              10:10002676   1.142180     1.118660         0.020592
1             10:100033081   0.849409     0.803559         0.053979
2              10:10004698   0.686901     0.575850         0.161670
3             10:100068607   0.941181     0.875650         0.069626
4             10:100076982   0.994909     1.020650         0.025873
...                    ...        ...          ...              ...
193629          9:99959341   1.286830     1.423020         0.105834
193630          9:99979829   0.730324     0.659314         0.097231
193631          9:99981843   1.011900     1.014090         0.002164
193632           9:9998777   0.975574     0.920400         0.056555
193633          9:99987850   1.003790     1.005590         0.001793

[193634 rows x 4 columns]

In [ ]:
# analyze with effect of ps

In [ ]:
# also check that the correct markers assoc and conditions assoc. are showing up

### Run GWAS at different levels of e and see how strength of association changes

In [93]:
import pickle
bundle = {
    "iid_order": iid_order,                          # list/array
    "genetic_subgroups": genetic_subgroups,          # list/array/Series
    "phenotypic_subgroups": phenotypic_subgroups,    # list/array/Series
    "markers_assoc": markers_assoc_dict,             # dict: gen_subgroup -> [marker_id, ...]
    "clinical_assoc": clinical_assoc_df              # pandas DataFrame
}

with open("/gpfs/commons/groups/gursoy_lab/anewbury/unsupervised_pheno/data/simulations/output/bundle.pkl", "wb") as f:
    pickle.dump(bundle, f, protocol=pickle.HIGHEST_PROTOCOL)

# load
with open("/gpfs/commons/groups/gursoy_lab/anewbury/unsupervised_pheno/data/simulations/output/bundle.pkl", "rb") as f:
    data = pickle.load(f)
data

{'iid_order': array(['HG02922', 'HG02923', 'HG02938', ..., 'HG04210', 'HG04227',
        'HG04229'], dtype=object),
 'genetic_subgroups':           IID    r  genetic_subgroup  subgroup subgroup_value
 0     HG02922  844                 0      True              0
 1     HG02923  837                 0      True              0
 2     HG02938  867                 0      True              0
 3     HG02941  839                 0      True              0
 4     HG02943  850                 0      True              0
 ...       ...  ...               ...       ...            ...
 2499  HG04106  683                 1     False
 2500  HG04107  722                 1     False
 2501  HG04210  690                 1     False
 2502  HG04227  709                 1     False
 2503  HG04229  730                 1     False

 [5008 rows x 5 columns],
 'phenotypic_subgroups':           IID     r  phenotypic_subgroup  subgroup
 0     HG02922   844                    0      True
 1     HG02923   837                    0      True
 2     HG02938   867                    0      True
 3     HG02941   839                    0      True
 4     HG02943   850                    0      True
 ...       ...   ...                  ...       ...
 2499  HG04106  None                    3     False
 2500  HG04107  None                    3     False
 2501  HG04210  None                    3     False
 2502  HG04227  None                    3     False
 2503  HG04229  None                    3     False

 [10016 rows x 4 columns],
 'markers_assoc': {0: ['5:180077487',
   '1:41661732',
   '4:96813201',
   '4:21803010',
   '3:73698077',
   '13:86466455',
   '20:15452514',
   '19:44163061',
   '11:11359155',
   '2:112590989',
   '10:133834561',
   '10:69336882',
   '10:88318428',
   '12:57622119',
   '6:117406666',
   '20:14742830',
   '7:12783554',
   '9:92713864',
   '5:38843333',
   '13:34096845',
   '6:77435421',
   '20:30891226',
   '5:53934608',
   '9:138015107',
   '10:119177940',
   '3:50101468',
   '13:93292736',
   '21:27751176',
   '11:89332932',
   '14:106848067',
   '22:26979169',
   '1:162566331',
   '16:59345023',
   '6:113217970',
   '12:101673300',
   '5:72825899',
   '12:126869052',
   '4:102021544',
   '1:161676394',
   '17:74142891',
   '2:3350333',
   '6:62063307',
   '1:64666059',
   '6:130494681',
   '18:11485481',
   '5:65531178',
   '1:31268508',
   '1:211191060',
   '1:15555271',
   '18:59337079',
   '17:49484049',
   '11:21193385',
   '10:22382802',
   '10:115060426',
   '1:76752097',
   '18:25372486',
   '1:14793449',
   '5:42440062',
   '20:16778996',
   '1:238976597',
   '13:32717827',
   '2:7486188',
   '17:2264215',
   '6:77523518',
   '1:227278474',
   '18:48827575',
   '17:64860014',
   '17:40442730',
   '12:31653715',
   '18:13703306',
   '5:17110196',
   '2:102271911',
   '15:55495638',
   '20:34861127',
   '12:29808060',
   '2:4617298',
   '5:120428910',
   '6:111095665',
   '8:90008085',
   '4:97184291',
   '8:124458650',
   '8:32035790',
   '11:15770954',
   '18:36043692',
   '19:785827',
   '3:140246245',
   '4:139298477',
   '2:242436608',
   '21:38420122',
   '20:34323553',
   '11:112960387',
   '18:7367496',
   '3:30009313',
   '4:70071988',
   '5:50219858',
   '2:197860033',
   '13:27013878',
   '1:163329394',
   '4:154835857',
   '2:210129416',
   '11:64803206',
   '14:35551875',
   '2:161726622',
   '9:99515284',
   '3:190951472',
   '20:24713823',
   '6:123071359',
   '6:134613732',
   '12:74090063',
   '7:100089017',
   '12:85466292',
   '5:44404545',
   '2:50801850',
   '2:101463972',
   '4:55306308',
   '21:18478555',
   '7:3047497',
   '5:25966784',
   '10:17123439',
   '7:89861832',
   '1:109961062',
   '20:7756027',
   '13:50153526',
   '3:33901658',
   '1:193292756',
   '18:73571312',
   '1:79872683',
   '1:8911409',
   '2:28137534',
   '14:41794462',
   '10:71195853',
   '11:31959932',
   '13:41393789',
   '7:46065952',
   '20:60107945',
   '10:64840901',
   '6:139134754',
   '2:103387525',
   '7:66769981',
   '1:84365653',
   '15:80214476',
   '9:108014870',
   '2:154851658',
   '3:61259536',
   '2:191694230',
   '2:95458986',
   '6:117077450',
   '11:133497296',
   '16:79185824',
   '20:17766367',
   '5:86727027',
   '5:97742108',
   '6:8449161',
   '1:24913228',
   '22:44791343',
   '7:89801787',
   '15:25995318',
   '13:112754576',
   '5:2638496',
   '1:77026910',
   '10:82316976',
   '16:57634886',
   '22:44937441',
   '3:70395875',
   '11:34207445',
   '2:170047220',
   '2:184419596',
   '10:44676272',
   '19:29284477',
   '2:111940939',
   '1:209169453',
   '14:41498957',
   '7:51203557',
   '7:55993051',
   '10:116495377',
   '8:15314955',
   '1:206558103',
   '14:48550442',
   '11:106466094',
   '17:59640111',
   '1:196664793',
   '14:26583964',
   '3:3585329',
   '5:55015068',
   '10:71441178',
   '3:2862584',
   '17:43653398',
   '5:61750087',
   '4:29060984',
   '22:36505770',
   '20:8662222',
   '17:37527911',
   '1:40609369',
   '7:137663477',
   '5:7160718',
   '8:84324347',
   '11:49610287',
   '18:39698527',
   '2:210141743',
   '6:166935803',
   '5:19609838',
   '14:97353952',
   '6:135048564',
   '8:36820750',
   '5:68481661',
   '1:245850095',
   '20:50512086',
   '9:20030180',
   '15:20670682',
   '3:114157282',
   '2:17431940',
   '6:8271755',
   '7:31600021',
   '2:64522307',
   '2:102315057',
   '11:17569392',
   '14:42956575',
   '13:33017937',
   '5:134347171',
   '1:3258534',
   '2:75801481',
   '9:134013274',
   '18:45981665',
   '2:80743370',
   '10:52496795',
   '4:43485665',
   '3:165843733',
   '16:81065059',
   '8:122002754',
   '2:207973529',
   '2:150834723',
   '20:47036440',
   '22:35079267',
   '3:9055695',
   '3:34173605',
   '11:110856108',
   '12:32189214',
   '4:159827313',
   '15:36579458',
   '7:98361817',
   '1:217709890',
   '16:13871313',
   '5:166190308',
   '5:86126228',
   '14:24222386',
   '16:3243177',
   '2:235979614',
   '1:180182972',
   '1:79384746',
   '22:50700723',
   '11:43144664',
   '2:65108532',
   '11:87634881',
   '12:45899821',
   '10:34417447',
   '10:23697244',
   '14:28371428',
   '3:162602810',
   '6:96590532',
   '14:55156456',
   '7:19864026',
   '6:160618157',
   '7:103489875',
   '7:38809967',
   '2:124453233',
   '5:85355019',
   '8:129023025',
   '21:32791689',
   '15:40953185',
   '4:17855912',
   '1:221672149',
   '7:98345589',
   '1:118548729',
   '10:119067684',
   '14:21053257',
   '12:20091101',
   '8:6514346',
   '20:17071181',
   '18:7932656',
   '4:47777122',
   '4:147272182',
   '11:40048416',
   '7:22120796',
   '4:4101993',
   '2:164791764',
   '7:128509826',
   '17:17736713',
   '4:40788210',
   '10:93408007',
   '7:123814487',
   '15:64187338',
   '3:8093466',
   '1:53377551',
   '14:37644792',
   '8:102777503',
   '11:132843990',
   '10:65672791',
   '6:66568384',
   '22:45560584',
   '9:32028739',
   '2:54927987',
   '2:142941721',
   '12:3511160',
   '11:41410465',
   '2:60544642',
   '18:19589336',
   '18:49630917',
   '19:33382696',
   '11:98588288',
   '11:103305610',
   '6:169155307',
   '5:130002692',
   '16:10504327',
   '20:58097983',
   '4:32244159',
   '1:169214596',
   '12:22240158',
   '1:172683570',
   '9:65622842',
   '11:13926079',
   '4:58824655',
   '13:50147394',
   '5:116216123',
   '6:93540269',
   '12:22450613',
   '10:70219496',
   '7:153781935',
   '6:52202392',
   '11:86973249',
   '8:40964589',
   '8:75270755',
   '8:107016219',
   '5:145802858',
   '2:6157860',
   '1:102687920',
   '4:45332494',
   '8:74983727',
   '11:112464797',
   '1:28245101',
   '11:118759659',
   '3:109225326',
   '4:79426285',
   '1:66002660',
   '10:71263605',
   '10:113719764',
   '11:125101050',
   '7:147738798',
   '12:69488179',
   '2:83224194',
   '4:130813487',
   '3:31413176',
   '8:90244238',
   '10:81730629',
   '17:63706568',
   '1:242315354',
   '3:134154695',
   '3:2133995',
   '3:185946680',
   '3:12006746',
   '4:88201500',
   '4:186033693',
   '14:69889381',
   '18:46892773',
   '2:142993559',
   '14:33445698',
   '6:164008031',
   '13:109501965',
   '4:23529424',
   '1:181308070',
   '16:24743342',
   '1:185397272',
   '4:130840719',
   '11:121663127',
   '9:77580205',
   '4:15740114',
   '9:132278633',
   '13:60155445',
   '22:21266870',
   '13:65050239',
   '2:83106503',
   '2:182936987',
   '1:93809051',
   '6:91223044',
   '5:32134976',
   '3:133725820',
   '15:69604966',
   '4:132288656',
   '12:3762349',
   '6:149658101',
   '8:56407447',
   '3:109344817',
   '18:2962000',
   '4:156107860',
   '1:23817411',
   '7:52724177',
   '6:148409521',
   '8:90990479',
   '3:47841312',
   '5:123803341',
   '5:75493412',
   '8:2769465',
   '6:117813269',
   '2:3972403',
   '22:39131835',
   '18:71489160',
   '1:209342457',
   '7:156722575',
   '15:101004404',
   '6:146323883',
   '1:95457236',
   '1:97837564',
   '5:6342409',
   '10:110710975',
   '2:105961104',
   '6:57694289',
   '14:40792833',
   '1:44904588',
   '1:99197041',
   '8:5077135',
   '7:118296937',
   '5:173788393',
   '17:52457935',
   '1:9138728',
   '5:130512367',
   '3:86251553',
   '4:134385776',
   '18:8947707',
   '7:135794400',
   '3:82011708',
   '15:62402043',
   '15:65359535',
   '5:85964365',
   '17:77122667',
   '21:37171412',
   '7:23536398',
   '3:25645514',
   '1:41392785',
   '8:35073360',
   '10:105760287',
   '16:62331649',
   '17:48663357',
   '8:87037996',
   '3:52967560',
   '4:57200947',
   '14:86983516',
   '13:44911116',
   '13:76748017',
   '1:200841258',
   '3:26557721',
   '13:37019085',
   '16:77465036',
   '3:174835581',
   '11:74207300',
   '10:5941130',
   '2:188183918',
   '21:21364604',
   '6:170814115',
   '5:18431049',
   '5:155117252',
   '20:49611401',
   '3:129076537',
   '1:99333610',
   '3:163443843',
   '12:29822380',
   '4:133813687',
   '13:24444557',
   '2:105450775',
   '14:74100151',
   '1:193770519',
   '12:56942555',
   '9:106764671',
   '13:82083693',
   '11:85886481',
   '8:66973845',
   '3:37739511',
   '6:62608605',
   '4:95708358',
   '4:127948885',
   '17:14816224',
   '2:170341919',
   '11:62209798',
   '2:235346730',
   '9:17870271',
   '12:70261873',
   '3:109616484',
   '12:31566833',
   '15:36612688',
   '5:107422067',
   '9:27536733',
   '10:115000814',
   '3:158044096',
   '14:106376976',
   '18:28735118',
   '8:62670106',
   '4:48409555',
   '9:15296355',
   '1:20916791',
   '3:150683270',
   '1:116337664',
   '3:132006650',
   '3:85847263',
   '1:96216913',
   '11:91435248',
   '5:3113227',
   '12:65776840',
   '5:65881600',
   '6:131006699',
   '1:72480789',
   '5:124134642',
   '13:69369375',
   '16:34522350',
   '17:44348221',
   '4:167470291',
   '2:115589392',
   '2:242762197',
   '7:108586254',
   '18:25658066',
   '14:21776520',
   '15:67150721',
   '10:38556576',
   '3:25709645',
   '17:71182643',
   '7:152936446',
   '2:57514400',
   '11:7012482',
   '1:190975052',
   '10:57332485',
   '11:132287874',
   '11:112292360',
   '20:50303008',
   '4:5998065',
   '6:107308174',
   '17:59463629',
   '3:111643797',
   '7:34579919',
   '4:89815404',
   '12:119174871',
   '1:81757825',
   '5:74420422',
   '19:44856657',
   '11:73588240',
   '11:115326135',
   '1:81386869',
   '2:31699883',
   '15:24546265',
   '15:92157109',
   '5:109596993',
   '14:34319353',
   '4:151434711',
   '7:24263896',
   '18:61468085',
   '16:215106',
   '11:79027641',
   '4:95775101',
   '8:104140389',
   '1:36641729',
   '6:168692772',
   '3:103303915',
   '14:92079525',
   '8:104136325',
   '3:129663536',
   '4:147872764',
   '2:44938350',
   '13:52245973',
   '10:74280767',
   '9:86310403',
   '1:73477420',
   '2:198463090',
   '2:116268867',
   '8:143886319',
   '2:154598859',
   '13:111019278',
   '2:114282325',
   '22:49225497',
   '2:70901576',
   '6:132561782',
   '9:131186231',
   '4:8290903',
   '6:46471716',
   '16:48747433',
   '3:172026710',
   '11:87779292',
   '1:232144598',
   '5:23251835',
   '4:125901548',
   '8:130153404',
   '13:79858885',
   '8:1143250',
   '18:32324348',
   '3:100521497',
   '17:2223997',
   '10:57586185',
   '1:195712025',
   '8:92618470',
   '3:180587012',
   '9:97729136',
   '10:13297424',
   '14:68258982',
   '1:53855711',
   '6:19841493',
   '8:38893322',
   '1:3217525',
   '9:9001207',
   '11:21960194',
   '13:35354487',
   '4:177796385',
   '1:2951034',
   '20:38214335',
   '6:12786085',
   '1:199427773',
   '8:129448014',
   '3:160930984',
   '13:62643752',
   '8:104503235',
   '6:157199901',
   '1:30139073',
   '2:30986910',
   '1:91606998',
   '1:52371469',
   '15:24174569',
   '12:122051272',
   '3:94704462',
   '9:103292278',
   '2:191387612',
   '2:221862070',
   '7:46164316',
   '9:73881932',
   '19:714282',
   '13:21736133',
   '4:11291708',
   '7:114343576',
   '13:82195177',
   '2:62545177',
   '8:5081184',
   '16:21806883',
   '17:20978442',
   '3:182697971',
   '10:90767640',
   '16:77641195',
   '4:29149504',
   '5:65566306',
   '4:37216735',
   '6:29507310',
   '2:157513324',
   '5:100598645',
   '11:126041015',
   '5:9825600',
   '4:27758593',
   '2:23543484',
   '17:10310859',
   '8:73914296',
   '2:214040425',
   '6:9085531',
   '10:94903195',
   '7:16907294',
   '8:126547352',
   '2:66023039',
   '19:32809751',
   '12:57810813',
   '3:88250258',
   '4:99951140',
   '4:25933687',
   '18:45004808',
   '8:14417189',
   '18:10795041',
   '12:75125448',
   '1:105807476',
   '1:90191440',
   '12:41556039',
   '14:31927931',
   '5:17588898',
   '7:82704452',
   '1:158685363',
   '7:26034676',
   '6:10568452',
   '7:56967681',
   '7:99744572',
   '14:64133222',
   '15:94382959',
   '6:161733654',
   '12:13849435',
   '20:36920516',
   '13:33727148',
   '9:43727521',
   '6:151981001',
   '1:169579645',
   '18:25628982',
   '14:94686356',
   '8:135894953',
   '2:44689326',
   '7:51823612',
   '11:49085225',
   '3:36424686',
   '1:93777920',
   '8:72851657',
   '11:104233636',
   '16:48009730',
   '10:54683045',
   '17:62103515',
   '7:71365984',
   '4:90781655',
   '10:53898181',
   '19:22544165',
   '15:38013312',
   '2:233283074',
   '1:218097640',
   '13:50358053',
   '1:3445911',
   '17:48409998',
   '6:51674395',
   '8:139597921',
   '13:95993079',
   '11:117872734',
   '9:3722895',
   '6:131419022',
   '17:30646581',
   '4:126807095',
   '8:13817602',
   '5:135123274',
   '8:6082279',
   '7:50958967',
   '22:24381406',
   '13:61536893',
   '15:33014295',
   '2:155741426',
   '3:153748350',
   '8:138619120',
   '11:41763992',
   '10:104460035',
   '9:104487586',
   '1:84361608',
   '16:10053190',
   '4:143406773',
   '6:57988395',
   '20:24302600',
   '15:32633686',
   '20:52304108',
   '16:20391075',
   '8:7793837',
   '12:131942268',
   '5:111305878',
   '13:81030272',
   '7:67972154',
   '10:101633779',
   '1:18313317',
   '4:176132058',
   '4:90557486',
   '1:237810013',
   '19:33099336',
   '5:118990139',
   '4:121768496',
   '9:117710057',
   '2:140960219',
   '3:56839649',
   '2:211202144',
   '1:202892274',
   '6:54861045',
   '16:69278415',
   '3:165148727',
   '21:30749480',
   '20:14252599',
   '17:59448945',
   '3:72763447',
   '17:64455197',
   '5:103084146',
   '4:55909354',
   '5:117833501',
   '16:24431465',
   '7:43569868',
   '8:92993679',
   '18:8855778',
   '10:54016782',
   '1:110968836',
   '15:28275331',
   '17:64401012',
   '10:107851952',
   '12:84867083',
   '13:109353462',
   '4:180553763',
   '13:97521207',
   '5:116753487',
   '7:158210927',
   '21:39282854',
   '12:25130793',
   '7:150252819',
   '5:122254017',
   '10:92246550',
   '22:49779586',
   '11:4128845',
   '2:146768217',
   '10:4536118',
   '17:52518194',
   '2:39530472',
   '5:30283571',
   '7:28768853',
   '3:5450470',
   '10:61965009',
   '1:161858558',
   '20:48239644',
   '10:80369711',
   '6:97672051',
   '5:59094023',
   '6:23165525',
   '13:39437138',
   '2:207792361',
   '9:140769671',
   '18:47419247',
   '1:241885307',
   '20:2358745',
   '2:216198850',
   '20:51734501',
   '13:24934386',
   '7:21511188',
   '13:78195800',
   '2:241969679',
   '10:84844997',
   '13:99661601',
   '12:87713925',
   '22:23405088',
   '12:68899688',
   '2:168129752',
   '13:42082837',
   '6:159993180',
   '11:94090810',
   '19:16034714',
   '14:50696798',
   '2:114687483',
   '13:109355555',
   '4:164439790',
   '7:71641842',
   '3:60943573',
   '19:13467645',
   '1:173434174',
   '12:59370568',
   '6:38804405',
   '4:66456906',
   '16:74869353',
   '5:105900104',
   '11:98320683',
   '2:155430196',
   '3:164148169',
   '12:62525780',
   '6:54525093',
   '16:13626406',
   '1:181943198',
   '22:45101811',
   '5:570055',
   '3:117116341',
   '12:75528535',
   '7:76901907',
   '3:81084351',
   '13:21574520',
   '10:48522641',
   '3:86831752',
   '9:138824538',
   '6:5306399',
   '17:74958452',
   '11:103952727',
   '5:126369570',
   '17:37264755',
   '2:169096623',
   '7:31523155',
   '12:114660658',
   '17:25579883',
   '11:86535612',
   '9:101013842',
   '4:136316044',
   '6:112849571',
   '18:60019850',
   '6:156685642',
   '9:9832914',
   '7:123835078',
   '3:110536989',
   '1:177820329',
   '11:37054831',
   '17:50721684',
   '19:39459362',
   '18:62276702',
   '3:130249728',
   '8:57496248',
   '2:194232899',
   '6:2405116',
   '9:100868795',
   '17:32571230',
   '10:8337964',
   '2:55776793',
   '8:128083486',
   '18:61411973',
   '14:86647178',
   '8:13206776',
   '13:46420175',
   '14:21975781',
   '14:41945832',
   '12:119718002',
   '6:121954225',
   '19:30314666',
   '9:137567771',
   '11:32826081',
   '4:156002611',
   '9:138875968',
   '1:146769990',
   '2:243035962',
   '10:111044414',
   '22:44303489',
   '13:52098171',
   '2:214501632',
   '11:81611392',
   '11:34444031',
   '5:5999720',
   '9:126897258',
   '11:87835164',
   '21:32905354',
   '1:149607857',
   '12:62505234',
   '4:105078195',
   '9:3759525',
   '3:145168571',
   '1:102031541',
   '5:40965552',
   '6:107465718',
   '1:210646303',
   '14:41570895',
   '6:66319817',
   '15:70471277',
   '3:140000677',
   '8:133516071',
   '5:44887679',
   '20:41293746',
   '5:103304790',
   '12:95999698',
   '3:29195011',
   '7:128687487',
   '2:215903716',
   '12:18710291',
   '5:143558002',
   '3:33914289',
   '12:108283771',
   '9:38542255',
   '5:54697098',
   '5:93496811',
   '18:35720123',
   '9:132673694',
   '1:19019641',
   '3:69509352',
   '6:32525757',
   '8:43744126',
   '7:81536374',
   '2:41730127',
   '7:24152434',
   '8:80504861',
   '1:83322217',
   '2:6809817',
   '3:162523728',
   '3:162589822',
   '1:146720770',
   '17:2242586',
   '2:216762525',
   '12:115210372',
   '18:7524275',
   '7:38290825',
   '2:205791510',
   '4:59637184',
   '13:59724877',
   '12:47189295',
   '6:43125961',
   '21:39174042',
   '10:130217720',
   '11:131171000',
   '17:13695675',
   '1:247740871',
   '3:174083758',
   '19:8832439',
   '2:161306510',
   '7:9998308',
   '2:44151722',
   '12:27707059',
   '14:58691534',
   '9:23377275',
   '12:61034616',
   '14:54564443',
   '11:41817672',
   '1:227787987',
   '12:73011183',
   '2:10972738',
   '7:53569090',
   '10:127596105',
   '7:73210413',
   '16:31360963',
   '1:74181232',
   '16:61453060',
   '19:56864928',
   '2:31227031',
   '6:148484113',
   '9:111180694',
   '5:98976502',
   '15:95371345',
   '8:2789695',
   '1:187520753',
   '4:20121121',
   '4:108476825',
   ...],
  1: ['2:57710058',
   '9:71259727',
   '5:41617186',
   '1:24941854',
   '15:51183043',
   '2:30552223',
   '15:92392876',
   '3:41532364',
   '18:59246253',
   '12:81770143',
   '6:134156912',
   '4:95279214',
   '13:58754423',
   '7:66519848',
   '15:54586311',
   '19:18513703',
   '7:51821459',
   '1:112060375',
   '3:82581831',
   '11:108260467',
   '10:70219496',
   '12:48937282',
   '22:32940660',
   '12:52895879',
   '4:72515164',
   '1:146440682',
   '4:172929754',
   '6:62248129',
   '10:30984306',
   '15:81156953',
   '3:75132620',
   '13:20018419',
   '5:76199313',
   '7:50777491',
   '3:16207153',
   '20:15452514',
   '14:53413058',
   '21:43669228',
   '7:83433146',
   '10:78917488',
   '3:33273478',
   '2:218950036',
   '1:166510900',
   '8:120350167',

### Algorithm creation

In [ ]:
# empirically, show monotone decrease of loss and stabilization over iterations
# show stability of parameter norms (U^t-U^(t-1))

# JointMF
from algorithms.JointMF import *
writer = None

# read in simulated data
ps = 0.7
e = 0.5
C = np.load(f'{output_dir}/C_ps_{ps}_e_{e}.npy')
with open(f"{output_dir}/simulation_metadata_ps_{ps}_e_{e}.pkl", "rb") as f:
    simulation_metadata = pickle.load(f)

# read in covar file and X
covar = pd.read_csv(f'{intermediate_file_dir}/COVARIATE_FILE')
assert all(covar['IID'].values == simulation_metadata['iid_order']) # make sure all in same order
covar["Sex"] = (covar["Sex"] == "female").astype(int)
Z = covar.drop(['FID','IID'],axis=1).to_numpy()

plink_extract = f'''
module load plink/1.9 && plink --bfile {output_dir}/X \
    --recode A \
    --out {output_dir}/X
'''
result = subprocess.run(plink_extract, shell=True, check=True, executable="/bin/bash")
A,B,D,B_prime, D_prime, loss_history, success, message, max_mem, cpu_time, user_time = jmf(X, C, Z, rank=4, method='L-BFGS-B', writer=writer, options={'maxcor':5, 'maxiter':1000, 'gtol':1e-5, 'maxls':10, 'ftol':1e-5})

PLINK v1.90b6.21 64-bit (19 Oct 2020)          www.cog-genomics.org/plink/1.9/
(C) 2005-2020 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to /gpfs/commons/groups/gursoy_lab/anewbury/unsupervised_pheno/data/simulations/output/X.log.
Options in effect:
  --bfile /gpfs/commons/groups/gursoy_lab/anewbury/unsupervised_pheno/data/simulations/output/X
  --out /gpfs/commons/groups/gursoy_lab/anewbury/unsupervised_pheno/data/simulations/output/X
  --recode A

385553 MB RAM detected; reserving 192776 MB for main workspace.
193634 variants loaded from .bim file.
2504 people (0 males, 0 females, 2504 ambiguous) loaded from .fam.
Ambiguous sex IDs written to
/gpfs/commons/groups/gursoy_lab/anewbury/unsupervised_pheno/data/simulations/output/X.nosex
.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 2504 founders and 0 nonfounders present.
Calculating allele frequencies... 10111213141516171819202122232425262728293031323334353637383940414243444546474849505152535455565758596061626364656667686970717273747576777879808182838485868788899091929394959697989 done.
193634 variants and 2504 people pass filters and QC.
Note: No phenotypes present.
--recode A to
/gpfs/commons/groups/gursoy_lab/anewbury/unsupervised_pheno/data/simulations/output/X.raw
... 101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899done.

In [16]:
X_df = pd.read_csv(f'{output_dir}/X.raw', sep='\s+')
X_df

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [24]:
igsr_samples = read_in_igsr_samples(igsr_samples_filepath, bfile_path=f'{output_dir}/X')
igsr_samples['Superpopulation code'].unique()

array(['AFR', 'AMR', 'EAS', 'EUR', 'SAS'], dtype=object)

In [ ]:
ps_list = np.round(np.arange(0, 1.0, 0.1),1)
e_list = np.round(np.arange(0, 1.1, 0.1),1)
from simulations.genomes1000_sim import *
generate_umap_plot(mode='ps', var_list=ps_list, color_col='Superpopulation code',
                        color_label='Superpopulation', output_dir=output_dir,igsr_samples_filepath=igsr_samples_filepath)

# For e
generate_umap_plot(mode='e', var_list=e_list, color_col='subgroup_value', 
                        color_label='Genetic Subgroup', output_dir=output_dir)

/gpfs/commons/home/anewbury/miniconda/envs/jupyter/lib/python3.9/site-packages/plotnine/ggplot.py:587: PlotnineWarning: Saving 8 x 12 in image.
/gpfs/commons/home/anewbury/miniconda/envs/jupyter/lib/python3.9/site-packages/plotnine/ggplot.py:588: PlotnineWarning: Filename: /gpfs/commons/groups/gursoy_lab/anewbury/unsupervised_pheno/data/simulations/output/umap_clinical_ps.pdf
/gpfs/commons/home/anewbury/miniconda/envs/jupyter/lib/python3.9/site-packages/plotnine/ggplot.py:587: PlotnineWarning: Saving 8 x 12 in image.
/gpfs/commons/home/anewbury/miniconda/envs/jupyter/lib/python3.9/site-packages/plotnine/ggplot.py:588: PlotnineWarning: Filename: /gpfs/commons/groups/gursoy_lab/anewbury/unsupervised_pheno/data/simulations/output/umap_clinical_e.pdf