In [7]:
import pandas as pd
from plotnine import *
import os
import json
import numpy as np
from test_reconstruction import get_summary_df

colors_dict = {
"SCoNE":"#2f4b7c",
"MVBC":"#665191",
"RGWAS":"#a05195",  
"C-NMF":"#d45087",  
"C-CoNE":"#f95d6a",  
"G-NMF":"#ff7c43",  
"G-CoNE":"#ffa600",  
"HNMF":"#2ca02c",  
"SCoNE(Fro)":"#1f77b4",
"CoNE":"#17becf"
}

In [3]:
root_dir = '/home/jupyter/repos/SCoNE'
output_dir = f'{root_dir}/output'
os.makedirs(f'{output_dir}/figures',exist_ok=True)

In [ ]:
# make graph for ari
def simple_graph(summary,variable_name,x_axis_name,y_axis_name,output_path):
    p = (
    ggplot(summary[summary['run_name']=='SCoNE'], aes(variable_name, "mean", color='factor_matrix', group='factor_matrix'))
    + geom_point(size=2)
    + geom_line()
    + geom_errorbar(aes(ymin="ymin",ymax="ymax"),width=0.05)
    + scale_color_brewer(type="qual", palette="Paired")
    + labs(y=y_axis_name,x=x_axis_name,color="")
    + theme_minimal()
        + theme(panel_border=element_rect(color="black", fill=None, size=1),
            panel_grid_major=element_blank(),
        panel_grid_minor=element_blank(),
        figure_size=(4, 4),text=element_text(family='sans-serif',size=12),
        legend_position="top"
    )
    )
    print(p)
    p.save(f'{output_path}_baseline.pdf',dpi=300)

In [ ]:
# make graph for cosine similarity

In [5]:
df = pd.read_csv(f'/home/jupyter/repos/SCoNE/output/TESTING_rG_unobs_subgroup_results.csv', index_col=0)
df_train = df[df['split']=='train'].copy()
df_train.columns

Index(['ari', 'sim_W', 'sim_W_null', 'tuning_metric', 'run', 'split', 'sim_id',
       'job_id', 'sim_U_G', 'sim_U_G_null', 'sim_U_C', 'sim_U_C_null',
       'rel_error_G', 'rel_error_C', 'coph_corr', 'sim_H_G', 'sim_H_G_null',
       'sim_H_C', 'sim_H_C_null', 'run_name', 'lambda_option', 'rank',
       'subgroup_structure', 'out_path'],
      dtype='object')

In [9]:
# get summary for best params for split train
get_summary_df(df_train,["run_name", "sim_id", "job_id","rank", "subgroup_structure"],"ari")

,run_name,sim_id,job_id,rank,subgroup_structure,n,mean,std,se,ymin,ymax
0,HNMF,0,0,3,True,5,0.370864,0.012739,0.005697,0.365166,0.376561
1,HNMF,1,12,3,False,0,NaN,NaN,NaN,NaN,NaN
2,HNMF,2,19,4,True,5,0.209815,0.071362,0.031914,0.177900,0.241729
3,HNMF,3,31,4,False,0,NaN,NaN,NaN,NaN,NaN
4,HNMF(res),0,1,3,True,5,0.265697,0.004259,0.001905,0.263792,0.267602
5,HNMF(res),1,13,3,False,0,NaN,NaN,NaN,NaN,NaN
6,HNMF(res),2,20,4,True,5,0.040341,0.049483,0.022129,0.018212,0.062471
7,HNMF(res),3,32,4,False,0,NaN,NaN,NaN,NaN,NaN
8,MVBC,0,6,3,True,1,0.003937,NaN,NaN,NaN,NaN
9,MVBC,2,25,4,True,1,0.005745,NaN,NaN,NaN,NaN
10,SCoNE,0,8,3,True,5,0.444420,0.059931,0.026802,0.417618,0.471221
11,SCoNE,1,18,3,False,0,NaN,NaN,NaN,NaN,NaN
12,SCoNE,2,27,4,True,5,0.426941,0.064837,0.028996,0.397945,0.455937
13,SCoNE,3,36,4,False,0,NaN,NaN,NaN,NaN,NaN

In [10]:
df_train

,ari,sim_W,sim_W_null,tuning_metric,run,split,sim_id,job_id,sim_U_G,sim_U_G_null,...,coph_corr,sim_H_G,sim_H_G_null,sim_H_C,sim_H_C_null,run_name,lambda_option,rank,subgroup_structure,out_path
110,0.003937,0.241921,0.230795,-0.003937,0,train,0,6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,MVBC,1.000,3,True,/home/jupyter/repos/SCoNE/output/models/TESTIN...
111,0.005745,0.219115,0.241200,-0.005745,0,train,2,25,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,MVBC,1.000,4,True,/home/jupyter/repos/SCoNE/output/models/TESTIN...
112,NaN,NaN,NaN,1.205951,0,train,3,31,NaN,NaN,...,0.880288,NaN,NaN,NaN,NaN,HNMF,0.000,4,False,/home/jupyter/repos/SCoNE/output/models/TESTIN...
113,NaN,NaN,NaN,1.201269,1,train,3,31,NaN,NaN,...,0.880288,NaN,NaN,NaN,NaN,HNMF,0.000,4,False,/home/jupyter/repos/SCoNE/output/models/TESTIN...
114,NaN,NaN,NaN,1.199401,2,train,3,31,NaN,NaN,...,0.880288,NaN,NaN,NaN,NaN,HNMF,0.000,4,False,/home/jupyter/repos/SCoNE/output/models/TESTIN...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,0.438895,0.642088,0.327348,1.021909,0,train,2,27,0.906949,0.385521,...,0.946014,0.502701,0.322978,0.738805,0.327919,SCoNE,0.001,4,True,/home/jupyter/repos/SCoNE/output/models/TESTIN...
168,0.483913,0.659934,0.322028,1.021701,1,train,2,27,0.856077,0.367755,...,0.946014,0.505624,0.328787,0.748060,0.338536,SCoNE,0.001,4,True,/home/jupyter/repos/SCoNE/output/models/TESTIN...
169,0.318263,0.218638,0.325591,1.028316,2,train,2,27,0.945507,0.416482,...,0.946014,0.261791,0.299477,0.310071,0.346103,SCoNE,0.001,4,True,/home/jupyter/repos/SCoNE/output/models/TESTIN...
170,0.467134,0.657147,0.323743,1.021442,3,train,2,27,0.849402,0.333175,...,0.946014,0.502862,0.325500,0.719214,0.343345,SCoNE,0.001,4,True,/home/jupyter/repos/SCoNE/output/models/TESTIN...
171,0.426499,0.639100,0.328322,1.021283,4,train,2,27,0.878652,0.351833,...,0.946014,0.535969,0.338590,0.751612,0.338722,SCoNE,0.001,4,True,/home/jupyter/repos/SCoNE/output/models/TESTIN...

In [11]:
get_summary_df(df_train,["run_name", "sim_id", "job_id","rank", "subgroup_structure"],"sim_W")

,run_name,sim_id,job_id,rank,subgroup_structure,n,mean,std,se,ymin,ymax
0,HNMF,0,0,3,True,5,0.683980,0.009090,0.004065,0.679915,0.688045
1,HNMF,1,12,3,False,0,NaN,NaN,NaN,NaN,NaN
2,HNMF,2,19,4,True,5,0.250567,0.103763,0.046404,0.204163,0.296971
3,HNMF,3,31,4,False,0,NaN,NaN,NaN,NaN,NaN
4,HNMF(res),0,1,3,True,5,0.607065,0.001131,0.000506,0.606559,0.607570
5,HNMF(res),1,13,3,False,0,NaN,NaN,NaN,NaN,NaN
6,HNMF(res),2,20,4,True,5,0.375110,0.069009,0.030862,0.344249,0.405972
7,HNMF(res),3,32,4,False,0,NaN,NaN,NaN,NaN,NaN
8,MVBC,0,6,3,True,1,0.241921,NaN,NaN,NaN,NaN
9,MVBC,2,25,4,True,1,0.219115,NaN,NaN,NaN,NaN
10,SCoNE,0,8,3,True,5,0.752132,0.040211,0.017983,0.734149,0.770115
11,SCoNE,1,18,3,False,0,NaN,NaN,NaN,NaN,NaN
12,SCoNE,2,27,4,True,5,0.563382,0.192932,0.086282,0.477100,0.649663
13,SCoNE,3,36,4,False,0,NaN,NaN,NaN,NaN,NaN